### ISSUE TITLE
请问如果运行的python代码有误，怎么引导重试呢

### ISSUE THREAD

**Issue by JennieGao-njust** [TableLLM/TableLLM#3]
Header and first few lines of CSV file:
Name,Class,Gender,Student ID,Hometown,Subject,Math,Chinese,English,Comprehensiveness,Gaokao Score
Lili,202403,Male,2024023120,Heilongjiang,Liberal Arts,133,123,123,268,647
Xiaohua,202403,Female,2024023121,Liaoning,Science,136,120,130,264,650
Dahua,202403,Male,2024023122,Jilin,Science,138,113,132,266,649

上面是提供的表格， 提问是
Question:What is the percentage of female students?

得到的python代码是：
import pandas as pd
df = pd.read_csv('data.csv')
female_student_percentage = df['Female'].sum() / df.shape[0] * 100
print(female_student_percentage)

在female_student_percentage = df['Female'].sum() / df.shape[0] * 100 报错，应该是female_student_count = df[df['Gender'] == 'Female'].shape[0] 

在您给出的platform上 给的是正确的代码  如果给出的代码有误，怎么进行二次重试逻辑 让模型修正呢？

**Comment by Kaka23333** [comment]
您好，我们的模型暂时只支持单轮问答，无法通过您的反馈或执行器的错误信息进行错误修正；未来我们会参考[OpenCodeInterpreter](https://opencodeinterpreter.github.io/)的方案，支持多轮问答并根据反馈和错误信息进行错误修正。

**Comment by JennieGao-njust** [comment]
> 您好，我们的模型暂时只支持单轮问答，无法通过您的反馈或执行器的错误信息进行错误修正；未来我们会参考[OpenCodeInterpreter](https://opencodeinterpreter.github.io/)的方案，支持多轮问答并根据反馈和错误信息进行错误修正。

好的 感谢
